apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: task-app
description: task app deployment pipeline
serialPipeline:
 stages:
 - targetId: dev-target
   profiles: [dev]
 - targetId: prod-target
   profiles: [prod]
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: dev-target
description: Cloud Run development service
run:
 location: projects/task-app-nodejs-mongodb/locations/europe-west2
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: prod-target
description: Cloud Run production service
run:
 location: projects/task-app-nodejs-mongodb/locations/europe-west2